version: '3.4'
services:
  rest-desafio-stoom:
    image: jnsousa/desafio:v1
    restart: always
    build: ./../../desafio
    working_dir: /desafio
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
    - ../../../desafio:/desafio
    - ~/.m2:/root/.m2
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    networks:
      - desafio-network
networks:
  desafio-network:
    driver: bridge